# Main Configuration File for Project AI Assistant

# Search configuration
search:
  embedding_weight: 4.0    # Weight for embedding-based search results
  bm42_weight: 6.0         # Weight for BM42 search results (Qdrant)
  max_results: 10          # Maximum number of results to return
  min_score: 0.1           # Minimum score threshold for results
  overlap_bonus: 2.0       # Bonus multiplier for documents appearing in multiple searches
  overlap_priority: true   # Enable overlap prioritization (overlap documents ranked first)


# Database configuration
database:
  qdrant_host: "localhost"
  qdrant_port: 6333  # HTTP port for Qdrant (gRPC is 6334)
  collection_name: "jira_issues"
  bm42_collection: "jira_bm42_full"  # Collection for BM42 sparse vectors (full data)
  title_collection: "jira_titles"
  content_collection: "jira_contents"

# API configuration
api:
  embedding_server: "http://localhost:8080/v1"
  timeout: 30  # Timeout in seconds