name: Run tests

on:
  push:
    branches: ["main"]
    paths-ignore:
    - "**/*.md"
  pull_request:
    branches: ["main"]

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: checkout repository
      uses: actions/checkout@v4

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: go tests
      run: go test -race -v ./...
